"""
Document download routes — KB-14 doc generation extension.

Serves files from data/documents/ with authentication.
Endpoint: GET /api/v1/documents/{file_id}
"""
import mimetypes
import os
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import FileResponse

from api.security_dependencies import require_2fa
from utils.logger import setup_logger

logger = setup_logger(__name__)

router = APIRouter(prefix="/api/v1/documents", tags=["documents"])

# Resolve the documents directory relative to this file's project root
_PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
_DOCUMENTS_DIR = (_PROJECT_ROOT / "data" / "documents").resolve()

# Allowed MIME types — only known document/image types are served
_ALLOWED_MIME_PREFIXES = (
    "application/vnd.openxmlformats-officedocument.",
    "application/vnd.oasis.opendocument.",
    "application/pdf",
    "text/html",
    "image/svg+xml",
    "image/png",
    "image/jpeg",
)

_EXT_MIME = {
    ".docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    ".pptx": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    ".xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    ".pdf":  "application/pdf",
    ".html": "text/html",
    ".htm":  "text/html",
    ".odt":  "application/vnd.oasis.opendocument.text",
    ".svg":  "image/svg+xml",
    ".png":  "image/png",
    ".jpg":  "image/jpeg",
    ".jpeg": "image/jpeg",
}


def _resolve_safe(file_id: str) -> Path:
    """
    Resolve file_id to an absolute path inside _DOCUMENTS_DIR.
    Raises HTTPException 400 if path traversal is attempted.
    Raises HTTPException 404 if file does not exist.
    """
    # Reject any path separators or dots that could escape the directory
    if "/" in file_id or "\\" in file_id or ".." in file_id:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Invalid file_id")
    resolved = (_DOCUMENTS_DIR / file_id).resolve()
    # Assert the resolved path is still inside _DOCUMENTS_DIR
    try:
        resolved.relative_to(_DOCUMENTS_DIR)
    except ValueError:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Invalid file_id")
    if not resolved.exists():
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Document not found")
    return resolved


@router.get("/{file_id}", summary="Download a generated document")
async def download_document(
    file_id: str,
    _user: dict = Depends(require_2fa),
):
    """
    Download a file previously generated by render_diagram or export_document.
    Requires 2FA authentication. Files are served from data/documents/.
    """
    resolved = _resolve_safe(file_id)
    ext = resolved.suffix.lower()
    mime = _EXT_MIME.get(ext, "application/octet-stream")

    # Only serve known document/image types
    allowed = any(mime.startswith(p) for p in _ALLOWED_MIME_PREFIXES)
    if not allowed:
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="File type not servable")

    logger.debug(f"Serving document: {file_id} ({mime}, {resolved.stat().st_size} bytes)")
    return FileResponse(
        path=str(resolved),
        media_type=mime,
        filename=file_id,
        headers={"Content-Disposition": f'attachment; filename="{file_id}"'},
    )
