#!/usr/bin/env python3
"""
business_case skill handler.

Computes NPV, ROI, payback period and IRR from agent-supplied cash flows and
returns a structured business case markdown document.

Input:  {"parameters": {"project": "...", "initial_investment": N, "annual_benefits": [...],
          "annual_costs": [...], "discount_rate": 0.08, "currency": "EUR", ...}}
Output: {"success": true, "result": {"npv": N, "roi_pct": N, "payback_period_years": N,
          "irr_pct": N|null, "recommendation": "...", "cash_flows": [...],
          "business_case_markdown": "..."}}
"""
import json
import sys
import math


# ---------------------------------------------------------------------------
# Financial computations
# ---------------------------------------------------------------------------

def _npv_at_rate(rate: float, net_flows: list, initial_investment: float) -> float:
    return -initial_investment + sum(
        net_flows[t] / (1 + rate) ** (t + 1) for t in range(len(net_flows))
    )


def _compute_irr(net_flows: list, initial_investment: float):
    """Bisection method over [-50%, +500%]. Returns None if no sign change."""
    lo, hi = -0.5, 5.0
    npv_lo = _npv_at_rate(lo, net_flows, initial_investment)
    npv_hi = _npv_at_rate(hi, net_flows, initial_investment)
    if npv_lo * npv_hi >= 0:
        return None
    for _ in range(50):
        mid = (lo + hi) / 2.0
        if _npv_at_rate(mid, net_flows, initial_investment) > 0:
            lo = mid
        else:
            hi = mid
    return round((lo + hi) / 2.0 * 100, 2)


def _compute_payback(net_flows: list, initial_investment: float) -> float:
    """Returns payback period in years (float), or inf if never recovered."""
    cumulative = -initial_investment
    for t, flow in enumerate(net_flows):
        prev = cumulative
        cumulative += flow
        if cumulative >= 0 and prev < 0:
            # Interpolate within the year
            fraction = (-prev / flow) if flow != 0 else 1.0
            return round(t + fraction, 2)
    return float("inf")


# ---------------------------------------------------------------------------
# Markdown builder
# ---------------------------------------------------------------------------

def _fmt(value: float, currency: str) -> str:
    """Format a monetary value."""
    if math.isinf(value):
        return "N/A"
    return f"{currency} {value:,.2f}"


def _build_markdown(
    project: str,
    initial_investment: float,
    discount_rate: float,
    currency: str,
    cash_flows: list,
    npv: float,
    roi_pct: float,
    payback: float,
    irr_pct,
    recommendation: str,
    qualitative_benefits: list,
    qualitative_risks: list,
) -> str:
    rec_label = {"proceed": "PROCEED", "marginal": "MARGINAL — review further", "reject": "REJECT"}.get(
        recommendation, recommendation.upper()
    )

    lines = [
        f"# Business Case: {project}",
        "",
        "## Executive Summary",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Initial Investment | {_fmt(initial_investment, currency)} |",
        f"| Discount Rate | {discount_rate * 100:.1f}% |",
        f"| NPV | {_fmt(npv, currency)} |",
        f"| ROI | {roi_pct:.2f}% |",
        f"| Payback Period | {'N/A' if math.isinf(payback) else f'{payback:.2f} years'} |",
        f"| IRR | {'N/A' if irr_pct is None else f'{irr_pct:.2f}%'} |",
        f"| **Recommendation** | **{rec_label}** |",
        "",
        "## Cash Flow Analysis",
        "",
        f"| Year | Benefit ({currency}) | Cost ({currency}) | Net ({currency}) | Cumulative ({currency}) |",
        f"|------|-----------------|--------------|--------------|---------------------|",
    ]

    for cf in cash_flows:
        lines.append(
            f"| {cf['year']} | {cf['benefit']:,.2f} | {cf['cost']:,.2f} | {cf['net']:,.2f} | {cf['cumulative']:,.2f} |"
        )

    if qualitative_benefits:
        lines += ["", "## Qualitative Benefits", ""]
        for b in qualitative_benefits:
            lines.append(f"- {b}")

    if qualitative_risks:
        lines += ["", "## Qualitative Risks", ""]
        for r in qualitative_risks:
            lines.append(f"- {r}")

    lines += [
        "",
        "## Recommendation",
        "",
        f"**{rec_label}**",
        "",
        "_(Generated by business_case skill — verify assumptions with finance stakeholders)_",
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# execute
# ---------------------------------------------------------------------------

def execute(params: dict) -> dict:
    project = params.get("project", "Unnamed Project")
    initial_investment = float(params.get("initial_investment", 0))
    annual_benefits = [float(x) for x in params.get("annual_benefits", [])]
    annual_costs = [float(x) for x in params.get("annual_costs", [])]
    discount_rate = float(params.get("discount_rate", 0.08))
    currency = str(params.get("currency", "EUR"))
    qualitative_benefits = params.get("qualitative_benefits") or []
    qualitative_risks = params.get("qualitative_risks") or []

    if not annual_benefits:
        raise ValueError("annual_benefits must be a non-empty list")
    if len(annual_benefits) != len(annual_costs):
        raise ValueError("annual_benefits and annual_costs must have the same length")
    if initial_investment < 0:
        raise ValueError("initial_investment must be a positive number")

    # Net cash flows per year
    net_flows = [annual_benefits[i] - annual_costs[i] for i in range(len(annual_benefits))]

    # NPV
    npv = _npv_at_rate(discount_rate, net_flows, initial_investment)
    npv = round(npv, 2)

    # ROI
    total_net = sum(net_flows)
    roi_pct = round((total_net - initial_investment) / initial_investment * 100, 2) if initial_investment != 0 else 0.0

    # Payback
    payback = _compute_payback(net_flows, initial_investment)

    # IRR
    irr_pct = _compute_irr(net_flows, initial_investment)

    # Recommendation
    if npv > 0 and roi_pct > 15:
        recommendation = "proceed"
    elif npv > 0:
        recommendation = "marginal"
    else:
        recommendation = "reject"

    # Build cash flow table
    cash_flows = []
    cumulative = -initial_investment
    for i, (b, c, n) in enumerate(zip(annual_benefits, annual_costs, net_flows), 1):
        cumulative += n
        cash_flows.append({
            "year": i,
            "benefit": round(b, 2),
            "cost": round(c, 2),
            "net": round(n, 2),
            "cumulative": round(cumulative, 2),
        })

    markdown = _build_markdown(
        project, initial_investment, discount_rate, currency,
        cash_flows, npv, roi_pct, payback, irr_pct, recommendation,
        qualitative_benefits, qualitative_risks,
    )

    return {
        "npv": npv,
        "roi_pct": roi_pct,
        "payback_period_years": payback if not math.isinf(payback) else None,
        "irr_pct": irr_pct,
        "recommendation": recommendation,
        "cash_flows": cash_flows,
        "business_case_markdown": markdown,
    }


def main() -> None:
    if len(sys.argv) < 3:
        print("Usage: handler.py input.json output.json", file=sys.stderr)
        sys.exit(1)
    try:
        data = json.loads(open(sys.argv[1]).read())
        result = execute(data.get("parameters", {}))
        output = {"success": True, "result": result, "error": None, "logs": []}
    except Exception as exc:
        output = {"success": False, "result": None, "error": str(exc), "logs": []}
    with open(sys.argv[2], "w") as f:
        json.dump(output, f)


if __name__ == "__main__":
    main()
